package com.lti.dao;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;

import com.lti.entity.Customer;
import com.lti.util.JPAUtil;

public class CustomerDao {
	//code to insert customer data in the database using ORM
	public  void store(Customer customer) {
		
		//STEP- 1 = Create/Obtain EntityManagerFactory object
		EntityManagerFactory emf =JPAUtil.getEntityManagerFactory();

		
		//STEP-2 = Create EntityManager Object
		EntityManager em = emf.createEntityManager();
		
		//STEP-3 = Start or participate in a transaction
		EntityTransaction tx = em.getTransaction();
		tx.begin();
		
		//now we can insert update delete select whatever we want
		em.persist(customer); //insert query generated by this line with the help of "customer" object 
		tx.commit();
		
		//should be in a finally block
		em.close();
		emf.close();
	}

}
